version: 2.1

orbs: 
  codecov: codecov/codecov@3.2.2

jobs:
  build-and-test:
    macos:
      xcode: 13.3
    steps:
      - checkout
      - run:
          name: "Build"
          command: swift build
      - run:
          name: "Run tests"
          command: rake test
      - store_test_results:
          path: test-results
      - run:
          name: "Create code coverage report"
          command: rake codecov
      - codecov/upload:
          file: coverage/report

workflows:
  build-and-test:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - main
                - codecov
